name: Visitor Registration System Frontend Deployment
on:
  push:
    branches:
      - devops/CICD
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4

      - name: Install Dependencies
        run: npm install

      - name: Populate env file
        run: echo -e "REACT_APP_API_BASE_URL=${{ vars.REACT_APP_API_BASE_URL }}" > .env ; cat .env

      - name: Build React App
        run: CI=false; npm run build; ls -al

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}  
    
      - name: Log in to Amazon ECR Private
        id: login-ecr-private
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }} .

      - name: Push Docker image to Amazon ECR Private
        run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest  

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
              
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
          registry-type: public
      
      - name: Push Docker image to Amazon ECR public
        run: |
          docker tag ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest public.ecr.aws/z7w3s5l6/vrs-frontend:latest
          docker push public.ecr.aws/z7w3s5l6/vrs-frontend:latest